---
deployment:
  tasks:
    - export DEPLOYPATH=/home/munitarmagob/public_html/portal/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R funciones $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH